fun main(args: Array<String>) {
    println("Res: " + findSolution())
}

/**
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

Res:76576500
Solution: σ0(N)
https://en.wikipedia.org/wiki/Prime_omega_function
 */
private fun findSolution(): Long {
    val min = 10000 // 28 has 5
    val nThTriangleNumber = Long.MAX_VALUE

    for (nTh in min..nThTriangleNumber) {
        val triangleNumber = nTh.sequenceSumStartingFrom(1)
        if (triangleNumber % 2 != 0L && triangleNumber % 5 != 0L) {
            println(triangleNumber)
            continue
        }

        val numberOfDividers = triangleNumber.dividers()
        if (numberOfDividers >= 500L) {
            return triangleNumber
        }
    }

    return -1
}
