fun main(args: Array<String>) {
    println("Res: " + fib())
}

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
private fun fib(): Long {
    var fib = 1L
    var prev = 0L
    var temp: Long
    var resultSum = 0L
    while (true) {
        temp = fib + prev
        prev = fib
        fib = temp

        if (fib >= 4_000_000) {
            break
        }

        println(fib)

        if (fib % 2L == 0L) {
            resultSum += fib
        }
    }

    return resultSum
}